name: pulse_diagnosis
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.4.0
  flutter_otp_text_field: ^1.4.0+2
  cloud_firestore: ^5.6.1
  # google_sign_in: ^6.2.2
  flutter_bloc: ^8.1.6  
  
  url_launcher: ^6.3.1
  qr_code_dart_scan: ^0.9.4
  easy_localization: ^3.0.7+1
  http: ^1.3.0
  path_provider: ^2.1.5
  open_mail: ^0.0.7
  mobile_scanner: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/tabbar/
    
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
