name: pulse_diagnosis
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+6

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.4.0
  flutter_otp_text_field: ^1.4.0+2
  cloud_firestore: ^5.6.1
  # flutter_bloc: ^8.1.6  
  easy_localization: ^3.0.7+1
  http: ^1.3.0
  # path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  mobile_scanner: ^6.0.7
  percent_indicator: ^4.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/translations/ja-JP.json
    - assets/translations/en-US.json
    - assets/translations/tr-TR.json
    - assets/images/
    - assets/images/tabbar/
    
  
  fonts:
    - family: NotoSansJP  
      fonts:  
        - asset: assets/fonts/NotoSansJP-Regular.ttf  # Update with your font's path  
        - asset: assets/fonts/NotoSansJP-Bold.ttf    # If you have a bold variant  
          weight: 700  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
